# Generated by Django 3.2.2 on 2021-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pasword', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
            ],
        ),
    ]
