# Generated by Django 3.2.2 on 2021-05-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_activity_user_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='user_set',
        ),
    ]
