# Generated by Django 3.2.2 on 2021-05-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_course_user_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_set',
            field=models.ManyToManyField(related_name='course', to=settings.AUTH_USER_MODEL),
        ),
    ]
